# Generated by Django 4.1.3 on 2022-11-07 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepName', models.CharField(blank=True, max_length=100)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('CreatedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('CreatedDateTime', models.CharField(blank=True, max_length=100, null=True)),
                ('UpdatedBy', models.CharField(blank=True, max_length=100, null=True)),
                ('UpdatedDateTime', models.CharField(blank=True, max_length=100, null=True)),
                ('IsDeleted', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpId', models.CharField(blank=True, max_length=100)),
                ('Firstname', models.CharField(blank=True, max_length=100)),
                ('LastName', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('Password', models.TextField(blank=True, max_length=100)),
                ('ReportTold', models.CharField(blank=True, max_length=100)),
                ('CreatedById', models.CharField(blank=True, max_length=100)),
                ('CreatedDateTime', models.CharField(blank=True, max_length=100)),
                ('UpdatedById', models.CharField(blank=True, max_length=100)),
                ('UpdatedDateTime', models.CharField(blank=True, max_length=100)),
                ('IsDeleted', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTypeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeDescription', models.CharField(blank=True, max_length=100)),
                ('CreatedBy', models.CharField(blank=True, max_length=100)),
                ('CreatedDateTime', models.DateTimeField(blank=True, max_length=100)),
                ('UpdatedById', models.CharField(blank=True, max_length=100)),
                ('UpdatedDateTime', models.CharField(blank=True, max_length=100)),
                ('IsDeleted', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(blank=True, max_length=100)),
                ('LoginDateTime', models.CharField(blank=True, max_length=100)),
                ('EmpId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Longitude', models.CharField(max_length=100)),
                ('Lattitude', models.CharField(max_length=100)),
                ('AreaDescription', models.CharField(max_length=100)),
                ('AttendanceDate', models.DateTimeField()),
                ('AttendanceTime', models.DateTimeField()),
                ('EmpId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.employee')),
            ],
        ),
    ]
